const express = require('express')
const auth = require('../middleware/authentication.js')
const router = express.Router()
const {transfer, deposit, withdraw, TransactionHistory, balance} = require('../controllers/Money')
router.route('/transfer').post(auth, transfer)
router.route('/deposit').post(auth, deposit)
router.route('/withdraw').post(auth, withdraw)
router.route('/transactions').get(auth, TransactionHistory)
router.route('/balance').get(auth, balance)
module.exports = router