const express = require('express')
const passport = require('passport')
//const auth = require('../middleware/authentication.js')
const router = express.Router()
const {transfer, deposit, withdraw, TransactionHistory, balance} = require('../controllers/Money')
router.route('/transfer').post(passport.authenticate('jwt', { session: false }), transfer)
router.route('/deposit').post(passport.authenticate('jwt', { session: false }), deposit)
router.route('/withdraw').post(passport.authenticate('jwt', { session: false }), withdraw)
router.route('/transactions').get(passport.authenticate('jwt', { session: false }), TransactionHistory)
router.route('/balance').get(passport.authenticate('jwt', { session: false }), balance)
module.exports = router